### ISSUE TITLE
Dubbo new website design

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo-website#12]
The Dubbo new logo has been [accepted](https://github.com/apache/incubator-dubbo/issues/1961) by the community, we need to create the design based on the new logo.

**Comment by YujieQiyue** [comment]
Hi guys，I have designed the Dubbo Portal.Dubbo's product attributes is primarily connected, so the design uses lines as elements to achieve brand penetration.Let's take a look at the design.
![dubbo portal](https://user-images.githubusercontent.com/40591408/41894430-6fc22c42-7951-11e8-9234-0d56279c90f3.png)

**Comment by mercyblitz** [comment]
Nice design, clean and simple

**Comment by carryxyh** [comment]
like it.

**Comment by beiwei30** [comment]
looks good to me.

**Comment by zonghaishang** [comment]
Very professional ！If the homepage offers scrolling panels, it may be even better to have some wonderful videos in the community.

**Comment by ningyu1** [comment]
Clean and simple, nice design, the whole looks very comfortable

**Comment by terrymanu** [comment]
I like this design

**Comment by diecui1202** [comment]
Cool. +1

**Comment by lovepoem** [comment]
Awesome design

Jerrick Zhu <notifications@github.com> 于2018年6月26日周二 下午4:19写道：

**Comment by Jeff18521762447** [comment]
颜色太亮，看着眼睛好累

**Comment by Jukewu** [comment]
nice design.
maybe you can show more information in the frist screen of  each page.

**Comment by SoftwareKing** [comment]
辣眼睛，nice

**Comment by YujieQiyue** [comment]
Haha, now I display the original size of the design for easy viewing. Welcome everyone to make valuable suggestions.
![default](https://user-images.githubusercontent.com/40591408/42074343-50a2c714-7b9e-11e8-974f-e5f661c79f1e.png)
![docs](https://user-images.githubusercontent.com/40591408/42074349-5b6eed9e-7b9e-11e8-83ac-c47ee08cc5e2.png)
![blog](https://user-images.githubusercontent.com/40591408/42074352-65ecd5d8-7b9e-11e8-8e2b-e152333097c5.png)
![community](https://user-images.githubusercontent.com/40591408/42074357-6dd336fc-7b9e-11e8-8973-d3b4fca772d8.png)

**Comment by ralf0131** [comment]
@YujieQiyue  Really nice work! This will definitely help the developers to implement the website!

**Comment by EdwardLee03** [comment]
颜色确实有些亮，有些文字与背景颜色区分度不显著，看着眼睛有些累。建议照顾弱色或色盲群体，声明本人眼睛是正常的。😁
![_6200e61c-0a58-4f2a-a79c-382116f0e077](https://user-images.githubusercontent.com/1811851/42132352-0597f4ea-7d49-11e8-8f04-91b2a9586c5f.png)

**Comment by beiwei30** [comment]
+1, much much better than the current.

**Comment by ralf0131** [comment]
Thanks everyone for the comments.

This design has been implemented by https://github.com/apache/incubator-dubbo-website/pull/13

**Comment by YujieQiyue** [comment]
@EdwardLee03 Thank you for your advice! The color here uses the logo brand color, and it seems that it should adjust its brightness according to the specific scene.
