### ISSUE TITLE
http://dubbo.apache.org/zh-cn/docs/user/references/telnet.html Contains inaccessible links

### ISSUE THREAD

**Issue by zonghaishang** [apache/incubator-dubbo-website#134]
Website `http://dubbo.apache.org/zh-cn/docs/user/references/telnet.html contains` `扩展参考手册` and `Telnet 命令扩展`,  but not accessible now.

**Comment by htynkn** [comment]
I find them in here:
+ https://dubbo.gitbooks.io/dubbo-dev-book/content/impls/status-checker.html
+ https://dubbo.gitbooks.io/dubbo-dev-book/content/impls/telnet-handler.html
