### ISSUE TITLE
apache check failed, https://whimsy.apache.org/pods/project/dubbo

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo-website#160]
It uses `curl curl http://dubbo.incubator.apache.org`, and gets the html text, then checks it.

But now the html text is just a javascript code, so all check failed. We need to make sure the text right.

**Comment by purple-force** [comment]
The site has a redirect to specific language(zh-cn or en-us), can it change to `curl http://dubbo.incubator.apache.org/zh-cn/` or `curl http://dubbo.incubator.apache.org/en-us/`?

**Comment by diecui1202** [comment]
Maybe can not change. If not, what can we do to solve this problem?

**Comment by purple-force** [comment]
add check rules in `redirect.ejs`
