### ISSUE TITLE
Office Document Edit Error

### ISSUE THREAD

**Issue by carryxyh** [apache/incubator-dubbo-website#165]
https://github.com/apache/incubator-dubbo/issues/2659

**Comment by carryxyh** [comment]
https://github.com/apache/incubator-dubbo/issues/2659#issue-371491679

As this issue said, there is a error at doc:
```
<dubbo:reference interface="com.xxx.MenuService" group="*">
    <dubbo:method name="getMenuItems" merger="true" />
// it should be dubbo:reference
</dubbo:service>
```

**Comment by a601942905git** [comment]
how to do it?

**Comment by htynkn** [comment]
Fixed via https://github.com/apache/incubator-dubbo-website/pull/168
