### ISSUE TITLE
Translate the developer guide

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo-website#181]
Some files migrated  from dubbo wiki should be translated to Chinese：
https://github.com/apache/incubator-dubbo-website/tree/asf-site/docs/zh-cn/developers
```
1 、docs/zh-cn/developers/committer-guide/label-an-issue-guide_dev.md
2、docs/zh-cn/developers/committer-guide/website-guide_dev.md
3、 docs/zh-cn/developers/contributor-guide/cla-signing-guide_dev.md
4、docs/zh-cn/developers/contributor-guide/mailing-list-subscription-guide_dev.md
5、docs/zh-cn/developers/contributor-guide/software-donation-guide_dev.md
6、docs/zh-cn/developers/contributor-guide/new-contributor-guide_dev.md
7、docs/zh-cn/developers/user-guide/faq_dev.md

```
The English version are here

1 、docs/en-us/developers/committer-guide/label-an-issue-guide_dev.md
2、docs/en-us/developers/committer-guide/website-guide_dev.md
3、 docs/en-us/developers/contributor-guide/cla-signing-guide_dev.md
4、docs/en-us/developers/contributor-guide/mailing-list-subscription-guide_dev.md
5、docs/en-us/developers/contributor-guide/software-donation-guide_dev.md
6、docs/en-us/developers/contributor-guide/new-contributor-guide_dev.md
7、docs/en-us/developers/user-guide/faq_dev.md

**Comment by lixiaojiee** [comment]
the document no6 is finished

**Comment by lixiaojiee** [comment]
all the documents contains in this issue have been translated

**Comment by ralf0131** [comment]
Thanks @lixiaojiee for your contribution! I am closing it now.
