### ISSUE TITLE
 secondary directory in dubbo's developer guide is not responding

### ISSUE THREAD

**Issue by CrazyHZM** [apache/incubator-dubbo-website#183]
I want to reflect a problem, the User doc secondary directory in dubbo's developer guide is not responding.
Address：http://dubbo.apache.org/en-us/docs/dev/build.html
<img width="1439" alt="error_message" src="https://user-images.githubusercontent.com/19588788/48818860-0b8e2400-ed88-11e8-80ce-c4fcb6ac459e.png">

**Comment by CrazyHZM** [comment]
The browser I am using is Chrome 70.0.3538.102. Upgrading to the latest version 70.0.3538.110 has the same problem. The operating system is macOS 10.14.1.
My access to Safari is normal.

**Comment by lovepoem** [comment]
https://github.com/apache/incubator-dubbo/issues/2806

**Comment by CrazyHZM** [comment]
The network is normal.

**Comment by ralf0131** [comment]
The page works fine from my side. This does not looks like an issue of Dubbo website.

**Comment by ralf0131** [comment]
Looks like not a website issue, I am closing it. Please feel free to reopen if it still exist.
