### ISSUE TITLE
Link in user docs is 404

### ISSUE THREAD

**Issue by wetsion** [apache/incubator-dubbo-website#193]
Some extension links in user docs are 404, for example, in "User Doc"-"Demos"-"Cache Result", when i click 'Cache extension', jump to `http://dubbo.apache.org/books/dubbo-dev-book/impls/cache.html`.Please update links in user docs.
<br/>
用户文档里的一些扩展链接访问后404，例如点击「示例」-「结果缓存」中的“缓存扩展”链接，跳转到`http://dubbo.apache.org/books/dubbo-dev-book/impls/cache.html`后404，请更新文档中的链接

**Comment by ralf0131** [comment]
Hi, it is an issue, would you like to help to fix it?

To fix it, change the link in `/docs/en-us/user/demos/result-cache.md` to `../dev/impls/cache.md` should work. You can also find examples of the link format in quick-start.md. Remember to test it locally, see README for build instructions.

**Comment by caojiele** [comment]
@wetsion It should be "Result cache", no "Cache Result". please edit your comment. @ralf0131 this issue is closed.

**Comment by ralf0131** [comment]
@caojiele Thanks, I confirm it is fixed.
