### ISSUE TITLE
Dead link in Framework Design web page

### ISSUE THREAD

**Issue by biyuhao** [apache/incubator-dubbo-website#196]
In http://dubbo.apache.org/en-us/docs/dev/design.html

In design.md
```
More design principles refer to: [Framework design principle](./principals/introduction.md)
```
dead link to http://dubbo.apache.org/en-us/docs/dev/principals/introduction.html

**Comment by ralf0131** [comment]
Hi, it is an issue, because these  articles does not have English version, would you help to translate them into English?

To help on this issue (as an example), copy `/docs/zh-cn/dev/principals/code-detail.md` to `/docs/en-us/dev/principals/code-detail.md` and replace the content with English.

**Comment by biyuhao** [comment]
Sure! I'll take it from here.

**Comment by Bricks-Man** [comment]
> Sure! I'll take it from here.

You should commit a pull request so that they can fix it.

**Comment by biyuhao** [comment]
> > Sure! I'll take it from here.
> 
> You should commit a pull request so that they can fix it.

Hi, thanks for the reminder.
Have to admit, it's delayed.
I plan to spend some time in Chinese new year on this issue.
If you also want to contribute to this one, feel free to take it over.
Thank you again.

**Comment by caojiele** [comment]
@ralf0131 Please assigned to me, I can solve the issue.

**Comment by biyuhao** [comment]
hi @caojiele 
I have translated several files, would you mind to have a look and left some comment?
There are still several files to be done, maybe we can co-work on this.
It's located at #297

**Comment by caojiele** [comment]
> hi @caojiele
> I have translated several files, would you mind to have a look and left some comment?
> There are still several files to be done, maybe we can co-work on this.
> It's located at #297

hi, @biyuhao let us try.

**Comment by ralf0131** [comment]
> @ralf0131 Please assigned to me, I can solve the issue.

Sorry Github can only assign issue to committer...
If you want to take please leave a message and go ahead.

**Comment by caojiele** [comment]
> > @ralf0131 Please assigned to me, I can solve the issue.
> 
> Sorry Github can only assign issue to committer...
> If you want to take please leave a message and go ahead.

hahaha, I also want to become a committer.
