### ISSUE TITLE
Broken link in zipkin support blog post

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo-website#207]
In the last section of http://dubbo.apache.org/zh-cn/blog/use-zipkin-in-dubbo.html

Broken link: https://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/2.0.0.RC2/single/spring-cloud-sleuth.html#_dubbo_rpc_support

Should be: http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/2.0.1.RELEASE/single/spring-cloud-sleuth.html#_dubbo_rpc_support

**Comment by techyang** [comment]
This bug had been fixed. This issue can be closed.

**Comment by ralf0131** [comment]
Thanks.
