### ISSUE TITLE
switch language returns a empty page in blog detail page

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo-website#21]
http://dubbo.apache.org/en-us/blog/dubbo-meetup-beijing-may-12th-2018.html

When switch to Chinese, the page is empty. 

I suggest that we can provider a default page, when other language pages do not exist, show the default page.

The default page content is the guidance about how to contribute.

**Comment by ralf0131** [comment]
The current website return 404 when page does not exist. This looks good to me. I think this issue can be closed.

**Comment by caojiele** [comment]
@diecui1202 This page no problem.
