### ISSUE TITLE
Dead link problem summary

### ISSUE THREAD

**Issue by code4wt** [apache/incubator-dubbo-website#215]
Recently I found out that there are a lot of dead-link issues in dubbo-website, so I wrote a simple crawler to check the official website and found 30 dead-links. as follows:

|   entrance page (入口页面)   |   dead link (死链)   |
| ---- | ---- |
| http://dubbo.apache.org/en-us/blog/dubbo-101.html | http://dubbo.apache.org/books/dubbo-user-book/references/qos.html |
| http://dubbo.apache.org/en-us/blog/dubbo-new-async.html | https://github.com/dubbo/dubbo-samples/tree/samples-for-2.7.0-SNAPSHOT/dubbo-samples-async-original-future |
| http://dubbo.apache.org/en-us/blog/dubbo2-js.html | https://github.com/lexburner/Dubbojs-Learning |
| http://dubbo.apache.org/en-us/community/index.html | http://dubbo.apache.org/en-us/docs/user/references/protocol/rest.html |
| http://dubbo.apache.org/en-us/docs/user/demos/accesslog.html | http://services.It |
| http://dubbo.apache.org/en-us/docs/user/demos/config-connections.html | http://dubbo.apache.org/books/dubbo-user-book-en/demos/config-rule.html |
| http://dubbo.apache.org/en-us/docs/user/demos/group-merger.html | https://github.com/apache/incubator-dubbo/tree/master/dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/merge |
| http://dubbo.apache.org/en-us/docs/user/demos/logger-strategy.html | http://dubbo.apache.org/books/dubbo-dev-book-en/impls/logger-adapter.html |
| http://dubbo.apache.org/en-us/docs/user/demos/multi-registry.html | http://dubbo.apache.org/books/dubbo-dev-book-en/impls/registry.html |
| http://dubbo.apache.org/en-us/docs/user/demos/parameter-validation.html | https://github.com/apache/incubator-dubbo/tree/master/dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/validation |
| http://dubbo.apache.org/en-us/docs/user/demos/result-cache.html | https://github.com/apache/incubator-dubbo/tree/master/dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/cache |
| http://dubbo.apache.org/en-us/docs/user/demos/routing-rule.html | http://dubbo.apache.org/books/dubbo-dev-book-en/impls/router.html |
| http://dubbo.apache.org/en-us/docs/user/demos/service-container.html | http://dubbo.apache.org/books/dubbo-dev-book-en/impls/container.html |
| http://dubbo.apache.org/en-us/docs/user/recommend.html | http://dubbo-reg1.hst.xyi.cn.alidc.net:8080/status/com.alibaba.morgan.member.MemberService:1.0.5 |
| http://dubbo.apache.org/en-us/docs/user/references/protocol/rmi.html | http://download.oracle.com/docs/cd/E17409_01/javase/6/docs/technotes/guides/rmi/sunrmiproperties.html |
| http://dubbo.apache.org/en-us/docs/user/references/protocol/thrift.html | https://github.com/apache/incubator-dubbo/tree/master/dubbo-rpc/dubbo-rpc-thrift/src/test/java/com/alibaba/dubbo/rpc/protocol/thrift/examples |
| http://dubbo.apache.org/en-us/docs/user/references/registry/zookeeper.html | http://dubbo.apache.org/books/dubbo-admin-book/install/zookeeper.html |
| http://dubbo.apache.org/en-us/docs/user/references/telnet.html | http://dubbo.apache.org/books/dubbo-dev-book/impls/telnet-handler.html |
| http://dubbo.apache.org/zh-cn/blog/dubbo-contribue-to-opensource.html | https://github.com/apache/incubator-dubbo-website%E3%80%82%E5%90%8C%E6%A0%B7%E4%B9%9F%E6%98%AF%E4%B8%80%E4%B8%AA |
| http://dubbo.apache.org/zh-cn/blog/dubbo-new-async.html | https://github.com/dubbo/dubbo-samples/tree/samples-for-2.7.0-SNAPSHOT/dubbo-samples-async-generated-future |
| http://dubbo.apache.org/zh-cn/blog/prepare-an-apache-release.html | https://dist.apache.org/repos/dist/dev/incubator/dubbo/$%7Brelease_version%7D/ |
| http://dubbo.apache.org/zh-cn/blog/use-zipkin-in-dubbo.html | https://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/2.0.0.RC2/single/spring-cloud-sleuth.html |
| http://dubbo.apache.org/zh-cn/docs/dev/principals/configuration.html | http://download.oracle.com/javase/1.4.2/docs/guide/jar/jar.html |
| http://dubbo.apache.org/zh-cn/docs/user/coveragence.html | https://codecov.io/gh/apache/incubator-dubbo%E9%A1%B5%E9%9D%A2%E5%BE%97%E5%88%B0%E8%A6%86%E7%9B%96%E7%8E%87%E6%8A%A5%E8%A1%A8 |
| http://dubbo.apache.org/zh-cn/docs/user/demos/logger-strategy.html | http://dubbo.apache.org/books/dubbo-dev-book/impls/logger-adapter.html |
| http://dubbo.apache.org/zh-cn/docs/user/demos/multi-registry.html | http://dubbo.apache.org/books/dubbo-dev-book/impls/registry.html |
| http://dubbo.apache.org/zh-cn/docs/user/demos/parameter-validation.html | http://dubbo.apache.org/books/dubbo-dev-book/impls/validation.html |
| http://dubbo.apache.org/zh-cn/docs/user/demos/result-cache.html | http://dubbo.apache.org/books/dubbo-dev-book/impls/cache.html |
| http://dubbo.apache.org/zh-cn/docs/user/demos/routing-rule.html | http://dubbo.apache.org/books/dubbo-dev-book/impls/router.html |
| http://dubbo.apache.org/zh-cn/docs/user/demos/service-container.html | http://dubbo.apache.org/books/dubbo-dev-book/impls/container.html |

Anyone willing to fix these dead-links?

**Comment by techyang** [comment]
All have been done. this issue can be closed.

**Comment by ralf0131** [comment]
Thanks for the hard work! @techyang
