### ISSUE TITLE
Add Hangzhou meetup summary to blog

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo-website#237]
Add Hangzhou meetup summary to blog.
Also we need English version of Hangzhou Meetup and Chengdu Meetup summary.
If you would like to help, please leave a message.

**Comment by caojiele** [comment]
《用户指南》、《开发指南》翻译有人在做了吗？

**Comment by ralf0131** [comment]
@caojiele Not yet, please feel free to take it!

**Comment by caojiele** [comment]
ok!  But I see Dubbo Official website these two parts have been translated? Is conducted on the basis?Or resubmission? Finally, I can join the community to create?

**Comment by ralf0131** [comment]
Hi, if you found that the pages are translated, you can improve it. If there is not, please add a new page. Please send pull request to this repo.

**Comment by caojiele** [comment]
ok

**Comment by caojiele** [comment]
@ralf0131  #237 sir,You notice that the English version of this question refers to the lack of the two meetings of the blog in the community.

**Comment by caojiele** [comment]
@ralf0131  #252 my Pre is true?  but not have Hangzhou meetup summary of the blog in the community. I see that is Shenzhen meetup. right?

**Comment by lixiaojiee** [comment]
This issue has been fixed, I will close it now.
