### ISSUE TITLE
Bug for Dubbo Official WebSite

### ISSUE THREAD

**Issue by caojiele** [apache/incubator-dubbo-website#243]
1、http://dubbo.apache.org/zh-cn/docs/dev/principals/general-knowledge.html 文档底部
“谈谈扩充式扩展与增量式扩展”（http://dubbo.apache.org/zh-cn/docs/dev/principals/principals/expansibility.html） 报404，而正确的地址应该是http://dubbo.apache.org/zh-cn/docs/dev/principals/expansibility.html

2、http://dubbo.apache.org/zh-cn/docs/user/references/registry/zookeeper.html （zookeeper 注册中心）文档的zookeeper-安装中  “Zookeeper安装手册”链接地址报404；“ Quick Start “打开是http://dubbo.apache.org/zh-cn/docs/user/preface/usage.html （入门-用法），应该是http://dubbo.apache.org/zh-cn/docs/user/quick-start.html （快速启动）。

3、http://dubbo.apache.org/zh-cn/docs/user/demos/loadbalance.html  负载均衡策略中-ConsistentHash LoadBalance-算法参见：http://en.wikipedia.org/wiki/Consistent_hashing  链接延时响应打开。

4、http://dubbo.apache.org/zh-cn/docs/user/references/registry/redis.html  （Redis 注册中心）文档的安装中 “Redis安装手册”链接地址报404；“ Quick Start “打开是http://dubbo.apache.org/zh-cn/docs/user/preface/usage.html （入门-用法），应该是http://dubbo.apache.org/zh-cn/docs/user/quick-start.html （快速启动）。

5、http://dubbo.apache.org/zh-cn/docs/user/best-practice.html （服务化最佳实践）文档的序列化中“传值调用”和“传引用调用”链接延迟响应打开空白页。

6、http://dubbo.apache.org/zh-cn/docs/user/references/protocol/rmi.html  （协议参考手册- rmi:// )文档的 RMI配置 中 “JDK 文档”链接地址报404；（协议参考手册-thrift://） 文档的 使用 中 “dubbo 项目中的示例代码”链接地址报404。

7、http://dubbo.apache.org/zh-cn/docs/dev/principals/configuration.html （配置设计）  文档的 配置加载 中“ServiceProvider 规范”链接地址报404。

8、http://dubbo.apache.org/zh-cn/docs/dev/principals/dummy.html （防痴呆设计） 文档的 检查重复的jar包 中 “检查重复工具类” 示例代码中对&&的和大于逻辑判断符号的转义显示不正确。

9、http://dubbo.apache.org/zh-cn/docs/dev/contribution.html  （贡献） 文档的流程的第二点 “如果是改 BUG，或修改框架本身，可以从 Dubb 的 GitHub 上 Fork 工程。”中的"Dubb "单词拼写错误。

**Comment by ralf0131** [comment]
Hi, would you please send a pull request to fix it ?

**Comment by caojiele** [comment]
ok，I have the time that send a pull request to fix it.

**Comment by caojiele** [comment]
@ralf0131 I now see that's it, but should be able to write a crawler check the official website.

**Comment by ralf0131** [comment]
Someone has already done it. Please check https://github.com/apache/incubator-dubbo-website/issues/215. I am closing this issue now. Feel free to create a new one if you still found something wrong.

**Comment by caojiele** [comment]
Ok


原始邮件
发件人:Huxing Zhangnotifications@github.com
收件人:apache/incubator-dubbo-websiteincubator-dubbo-website@noreply.github.com
抄送:小码哥（Jack）caojiele1225@126.com; Authorauthor@noreply.github.com
发送时间:2019年1月17日(周四) 15:51
主题:Re: [apache/incubator-dubbo-website] Bug for Dubbo Official WebSite(#243)


Someone has already done it. Please check #215. I am closing this issue now. Feel free to create a new one if you still found something wrong.
