### ISSUE TITLE
There are typos in the picture

### ISSUE THREAD

**Issue by mimihom** [apache/incubator-dubbo-website#254]
http://dubbo.apache.org/en-us/docs/user/demos/explicit-target.html
http://dubbo.apache.org/zh-cn/docs/user/demos/explicit-target.html
`JVM Arugment` should be `JVM Argument`.

**Comment by caojiele** [comment]
pre一下

**Comment by ralf0131** [comment]
Would you please send a pull request to fix it?

**Comment by NikithaNadig** [comment]
Can I fix this issue? Or is it assigned to someone?

**Comment by caojiele** [comment]
@ralf0131 This issue has been corrected, can be closed.
