### ISSUE TITLE
Add release guide blog to developers page

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo-website#296]
The [blog](http://dubbo.apache.org/en-us/blog/prepare-an-apache-release.html) is an excellent writeup  about how to prepare for an Apache release, but it is difficult to find. We should move it to [here](http://dubbo.apache.org/en-us/docs/developers/committer-guide/release-guide_dev.html).

**Comment by caojiele** [comment]
@ralf0131 [here]（http://dubbo.apache.org/zh-cn/docs/developers/committer-guide/release-guide.html）This also need to change?

**Comment by ralf0131** [comment]
> @ralf0131 [here](http://dubbo.apache.org/zh-cn/docs/developers/committer-guide/release-guide.html)This also need to change?

Yes, please!

**Comment by caojiele** [comment]
@ralf0131 this issue is closed.
