### ISSUE TITLE
文档-建议

### ISSUE THREAD

**Issue by xixifeng** [apache/incubator-dubbo-website#314]
建议: 在每篇文档的底部加上链接, "发现错误？想参与编辑？ 在 GitHub 上编辑此页！" ,dubbo越来越好,离不开一点点的进步.

**Comment by htynkn** [comment]
<img width="850" alt="2019-03-06 2 10 05" src="https://user-images.githubusercontent.com/659135/53859732-92a29780-4019-11e9-8768-9140ed6ab1f0.png">

Good idea. Take serviceComb document as example, we can provide two option.
+ report doc issue
+ edit this page on github
