### ISSUE TITLE
Something error with local stub introduction

### ISSUE THREAD

**Issue by kexianjun** [apache/incubator-dubbo-website#329]
[Local Stub](http://dubbo.apache.org/en-us/docs/user/demos/local-stub.html) introduction has some error as following 
``` java
package com.foo;
public class BarServiceStub implements BarService {
    private final BarService barService;

    // The real remote proxy object is passed in through the constructor
    public (BarService barService) {
        this.barService = barService;
    }

    public String sayHello(String name) {
        // The following code is executed on the client. You can do local ThreadLocal caching on the client side, or verify parameters, etc.
        try {
            return barService.sayHello(name);
        } catch (Exception e) {
            // You can return the mock data.
            return "MockData";
        }
    }
}
```
the constructor's signature should be
```java
public BarServiceStub(BarService barService)
```

**Comment by caojiele** [comment]
> [Local Stub](http://dubbo.apache.org/en-us/docs/user/demos/local-stub.html) introduction has some error as following
> 
> ```java
> package com.foo;
> public class BarServiceStub implements BarService {
>     private final BarService barService;
> 
>     // The real remote proxy object is passed in through the constructor
>     public (BarService barService) {
>         this.barService = barService;
>     }
> 
>     public String sayHello(String name) {
>         // The following code is executed on the client. You can do local ThreadLocal caching on the client side, or verify parameters, etc.
>         try {
>             return barService.sayHello(name);
>         } catch (Exception e) {
>             // You can return the mock data.
>             return "MockData";
>         }
>     }
> }
> ```
> 
> the constructor's signature should be
> 
> ```java
> public BarServiceStub(BarService barService)
> ```
> 
> and
> 
> > <dubbo:service interface="com.foo.BarService" stub="true" />
> > <dubbo:service interface="com.foo.BarService" stub="com.foo.BarServiceStub" />
> 
> dubbo:service should be dubbo:reference

Modify the following:
```java
package com.foo;
public class BarServiceStub implements BarService {
    private final BarService barService;

    // The real remote proxy object is passed in through the constructor
    public BarServiceStub(BarService barService){
        this.barService = barService;
    }

    public String sayHello(String name) {
        // The following code is executed on the client. You can do local ThreadLocal caching on the client side, or verify parameters, etc.
        try {
            return barService.sayHello(name);
        } catch (Exception e) {
            // You can return the mock data.
            return "MockData";
        }
    }
}
```
right?

**Comment by kexianjun** [comment]
@caojiele and the dubbo:service should be dubbo:reference
![image](https://user-images.githubusercontent.com/12162539/54897070-e3632d00-4f01-11e9-8ffb-1daa4c0b1663.png)

**Comment by kexianjun** [comment]
@caojiele yes
