### ISSUE TITLE
spelling mistakes

### ISSUE THREAD

**Issue by JoeCqupt** [apache/incubator-dubbo-website#336]
http://dubbo.apache.org/zh-cn/docs/user/configuration/configuration-load-process.html

ctrl + f   "tineout"    modify to  "timeout"

**Comment by ralf0131** [comment]
Could you please send a pull request?

**Comment by JoeCqupt** [comment]
ok

**Comment by kezhenxu94** [comment]
@JoeCqupt Fixed in #341
