### ISSUE TITLE
Wrong maillinglist 

### ISSUE THREAD

**Issue by caojiele** [apache/incubator-dubbo-website#347]
In http://dubbo.apache.org/zh-cn/docs/developers/guide_dev.html
click the mailinglist dev@dubbo.incubator.apache.org
when called the mail application, you will see the mail address changed to
dev-subscribe@dubbo.incubator.apache.org

**Comment by kezhenxu94** [comment]
It's intentionally because to subscribe to the dev@dubbo.incubator.apache.org you need to mail to dev-subscribe@dubbo.incubator.apache.org
