### ISSUE TITLE
"cd dubbo-distribution/target" should be "cd dubbo-admin-distribution/target"

### ISSUE THREAD

**Issue by yobuke** [apache/incubator-dubbo-website#358]
"cd dubbo-distribution/target"
should be
"cd dubbo-admin-distribution/target"

**Comment by yobuke** [comment]
website:
http://dubbo.apache.org/zh-cn/docs/admin/introduction.html

**Comment by kezhenxu94** [comment]
@yobuke could you please send a pull request to fix this?

**Comment by kexianjun** [comment]
fixed
