### ISSUE TITLE
Add company name beneath company logo

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo-website#51]
In the "who is using Dubbo" section, there are many logos, but people may not know which company these logo represent. 

We need to add company name for each logo.

**Comment by majinkai** [comment]
Do it need to add a company's site address for each logo?

**Comment by ralf0131** [comment]
I don't think so. As an Apache project, I think it is better to keep neutral, therefore external links should be avoided.

**Comment by diecui1202** [comment]
I think it's unnecessary. Most of the logos contain the names.

**Comment by ralf0131** [comment]
@diecui1202 How about users does not know Chinese?
