### ISSUE TITLE
Highlight the number of github stars/forks in the dubbo homepage

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo-website#69]
Many open source projects do this, e.g. Apache RocketMQ, CNCF prometheus.

**Comment by diecui1202** [comment]
Any thoughts?

**Comment by caojiele** [comment]
This can be centered on the bottom of the page, similar to the copyright information.

**Comment by Bricks-Man** [comment]
I think you can use this [project](http://ghbtns.com/).

**Comment by lovepoem** [comment]
close via https://github.com/apache/incubator-dubbo-website/pull/309
